field: fc742864-ee45-41b8-b5f1-652355c49075
fieldLayouts:
  653d9691-9f52-4512-a1ad-c3bd1930d86f:
    tabs:
      -
        fields:
          7006dd9e-3313-4783-b284-d2587925996f:
            required: true
            sortOrder: 1
          e6b3dca0-bc3f-4b3b-b03e-daf577663c8f:
            required: true
            sortOrder: 2
        name: Content
        sortOrder: 1
fields:
  7006dd9e-3313-4783-b284-d2587925996f:
    contentColumnType: string
    fieldGroup: null
    handle: headingSize
    instructions: ''
    name: 'Heading size'
    searchable: true
    settings:
      options:
        -
          __assoc__:
            -
              - label
              - H2
            -
              - value
              - h2
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - H3
            -
              - value
              - h3
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  e6b3dca0-bc3f-4b3b-b03e-daf577663c8f:
    contentColumnType: text
    fieldGroup: null
    handle: headingText
    instructions: ''
    name: 'Heading text'
    searchable: true
    settings:
      charLimit: ''
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: heading
name: Heading
sortOrder: 1
