handle: storyCovers
hasUrls: true
name: 'Story Covers'
settings:
  autoFocalPoint: ''
  bucket: short-stories
  bucketSelectionMode: choose
  cfDistributionId: ''
  cfPrefix: ''
  expires: ''
  keyId: $AWS_ACCESS_KEY_ID
  makeUploadsPublic: '1'
  region: eu-west-1
  secret: $AWS_SECRET_ACCESS_KEY
  storageClass: ''
  subfolder: story-covers
sortOrder: 4
type: craft\awss3\Volume
url: $AWS_S3_URL
