contentColumnType: string
fieldGroup: c6a8cf07-e8f1-48db-a89c-b02f0a7a1c91
handle: memberLikes
instructions: 'Stories the user has liked'
name: Likes
searchable: '1'
settings:
  limit: ''
  localizeRelations: false
  selectionLabel: ''
  source: null
  sources:
    - 'section:4'
  targetSiteId: null
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: modules\fields\Entries
