contentColumnType: boolean
fieldGroup: c6a8cf07-e8f1-48db-a89c-b02f0a7a1c91
handle: memberVerified
instructions: 'If the member has been verified based on the number of followers they have'
name: Verified
searchable: '1'
settings:
  default: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
