contentColumnType: text
fieldGroup: c6a8cf07-e8f1-48db-a89c-b02f0a7a1c91
handle: memberBio
instructions: ''
name: Bio
searchable: '1'
settings:
  charLimit: '600'
  columnType: text
  initialRows: '4'
  multiline: '1'
  placeholder: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
