contentColumnType: text
fieldGroup: c6a8cf07-e8f1-48db-a89c-b02f0a7a1c91
handle: memberUsername
instructions: ''
name: Username
searchable: true
settings:
  charLimit: '20'
  code: ''
  columnType: text
  initialRows: '4'
  multiline: ''
  placeholder: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
