contentColumnType: boolean
fieldGroup: c6a8cf07-e8f1-48db-a89c-b02f0a7a1c91
handle: memberUpdated
instructions: "Test if members account has been updated for account update.\r\n\r\nThis has nothing to do with the functionality of the site."
name: Updated
searchable: '1'
settings:
  default: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
