contentColumnType: string(255)
fieldGroup: c6a8cf07-e8f1-48db-a89c-b02f0a7a1c91
handle: memberInstagramUrl
instructions: ''
name: 'Instagram URL'
searchable: true
settings:
  maxLength: '255'
  placeholder: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Url
