contentColumnType: boolean
fieldGroup: c6a8cf07-e8f1-48db-a89c-b02f0a7a1c91
handle: memberRequestedVerification
instructions: 'Has the member requested to be verified'
name: 'Requested verification?'
searchable: '1'
settings:
  default: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
