contentColumnType: text
fieldGroup: 34cac1b4-f567-4d44-b565-905df2d71cd0
handle: storyReadTime
instructions: "Get the story read time with a time attr.\r\nRounded to the closest number."
name: 'Story read time'
searchable: true
settings:
  allowSelect: false
  columnType: text
  decimals: '0'
  displayType: textinput
  fieldTwig: "{% set storyContent = entry.storyContent | editor %}\r\n{% set time = storyContent | readTime %}\r\n{% set timeRounded = time|round(0) %}\r\n{{ timeRounded > 1 ? timeRounded ~ ' mins' : '< 1 min'  }}"
  parseBeforeSave: false
  parseOnMove: false
  showField: false
  textareaRows: '5'
translationKeyFormat: null
translationMethod: none
type: aelvan\preparsefield\fields\PreparseFieldType
