contentColumnType: text
fieldGroup: 34cac1b4-f567-4d44-b565-905df2d71cd0
handle: storyReadTimeMin
instructions: "Read time tag - Including story read time.\r\nRounded to the closest number."
name: 'Story read time minutes'
searchable: true
settings:
  allowSelect: false
  columnType: text
  decimals: '0'
  displayType: textinput
  fieldTwig: "{% set storyContent = entry.storyContent | editor %}\r\n{% set time = storyContent | readTime %}\r\n{{ time < 1 ? '< 1' : time|round(0) }} min read"
  parseBeforeSave: false
  parseOnMove: false
  showField: false
  textareaRows: '5'
translationKeyFormat: null
translationMethod: none
type: aelvan\preparsefield\fields\PreparseFieldType
