contentColumnType: boolean
fieldGroup: 34cac1b4-f567-4d44-b565-905df2d71cd0
handle: storyContainsBadWords
instructions: ''
name: 'Contains bad words'
searchable: true
settings:
  default: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
