contentColumnType: text
fieldGroup: 34cac1b4-f567-4d44-b565-905df2d71cd0
handle: storyWordCount
instructions: ''
name: 'Story word count'
searchable: false
settings:
  allowSelect: false
  columnType: text
  decimals: '0'
  displayType: textinput
  fieldTwig: "{% set storyContent = entry.storyContent | editor %}\r\n{% set wordCount = storyContent | wordCount %}\r\n{{ wordCount }}"
  parseBeforeSave: false
  parseOnMove: false
  showField: false
  textareaRows: '5'
translationKeyFormat: null
translationMethod: none
type: aelvan\preparsefield\fields\PreparseFieldType
