contentColumnType: text
fieldGroup: aab80d77-85b7-4c95-a616-05f06c738358
handle: verificationBadgeContent
instructions: ''
name: 'Verification badge content'
searchable: '1'
settings:
  availableTransforms: ''
  availableVolumes:
    - '4'
  columnType: text
  purifierConfig: ''
  purifyHtml: '1'
  redactorConfig: StandardWithImages.json
  removeEmptyTags: '1'
  removeInlineStyles: '1'
  removeNbsp: '1'
translationKeyFormat: null
translationMethod: none
type: craft\redactor\Field
