enableVersioning: true
handle: help
name: Help
previewTargets:
  -
    label: 'Primary entry page'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  8539cb22-f67d-4219-8f6e-da97f89e6196: # $SITE_NAME
    enabledByDefault: true
    hasUrls: true
    template: help/_entry
    uriFormat: '{% if level == 1 %}help{% else %}{parent.uri}{% endif %}/{slug}'
structure:
  maxLevels: '2'
  uid: 4633fc6d-1f6e-47c3-9dce-0dd7a754d637
type: structure
